### ISSUE TITLE
Reloading the genome

### ISSUE THREAD

**Issue by sabrasisler** [feagi/feagi#126]
When using the reload genome button on the GUI, sometimes when switching genomes, weird things happen where cortical areas that don't exist are still present in Godot (three of the four active areas are ghost areas if you will). I tried refreshing the page, but they still didn't disappear. This issue came about when using the conditioned_avoidance_3 genome and switching the the brightness_detection genome. The two genomes are setup for different numbers of motors in the motor OPU, which could be the issue, but I don't see why that would cause this sort of bug.
![image](https://user-images.githubusercontent.com/52722031/180283649-568185d1-4337-4da4-b17a-dded7e6b4f7d.png)

**Comment by Kakcalu13** [comment]
This issue is addressed by websocket and this issue is very old now.
