### ISSUE TITLE
Selecting a custom map and robot is unreliable

### ISSUE THREAD

**Issue by sabrasisler** [feagi/feagi#152]
When I first tried to test a genome using the current staging branch, I selected the black map with white circles and the red smart-car. The red car wasn't properly loaded (instead there was a four wheeled green robot that wasn't even an option) and the map was the default grassy map, not the  black map. After multiple tries, I was able to get the black map successfully loaded, but very inconsistently.

**Comment by Kakcalu13** [comment]
https://github.com/feagi/feagi/pull/180 addressed this issue and it's fixed now.

Closing
