### ISSUE TITLE
Websocket error on latest  JS webcam controller

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/feagi#414]
The latest JS webcam controller push dated Nov 22nd 2023 is causing ws errors as shown below.

<img width="1920" alt="image" src="https://github.com/feagi/feagi/assets/26581495/057c0bb9-53d7-46f7-8381-7a4590d52560">

**Comment by Kakcalu13** [comment]
This is not an error, it just let you know whenever the client is disconnected or closed
