### ISSUE TITLE
Deleting a region and raising internals does not delete the region from summary view

### ISSUE THREAD

**Issue by Amir-Rasteg** [feagi/feagi#472]
Issue: deleting a region via the /v1/region/region endpoint returns a 200, however running /v1/region/region_members still shows that region as existing

![image](https://github.com/feagi/feagi/assets/127231771/3c9f5847-b25d-4037-94b4-d9e12f546774)

![image](https://github.com/feagi/feagi/assets/127231771/f1f3991f-7624-49df-9750-d4296c7cc5d4)

**Comment by Amir-Rasteg** [comment]
@m-nadji-tehrani

**Comment by m-nadji-tehrani** [comment]
fixed
